foodify/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :users, :only => [:show, :destroy] do
    resources :playlists do
      resources :items, except: :index
    end
  end

  root 'homes#index'
  get '/search' => 'homes#search'

end

foodify/app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :playlist
  belongs_to :restaurant

  validates :name, presence: true

end

foodify/app/models/playlist.rb
class Playlist < ActiveRecord::Base
  belongs_to :user
  has_many :items

  validates :name, presence: true

end

foodify/app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  has_many :items

  validates :name, presence: true

end

foodify/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :playlists

  validates :first_name, presence: true
  validates :last_name, presence: true

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

foodify/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

foodify/app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

  def search
    location = params[:location]
    parameters = { term: params[:term], limit: 5 }
    yelp_search = Yelp.client.search(location, parameters)
    @results = yelp_search.businesses
  end

end

foodify/app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def index
  end

  def search
    location = params[:location]
    parameters = { term: params[:term], limit: 5 }
    yelp_search = Yelp.client.search(location, parameters)
    @results = yelp_search.businesses
  end

end

foodify/app/controllers/item_controller.rb
class ItemController < ApplicationController

  def new
  end

  def show
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end

end

foodify/app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def new
    user = User.find(params[:user_id])
    if current_user == user
      @item = Item.new
    else
      redirect_to new_user_session_path
    end
  end

  def create
    @item = Item.new(item_params)
    @playlist = Playlist.find(params[:playlist_id])
    @item.playlist = @playlist

    # Yelp's search results
    # location = params[:location]
    # parameters = { term: params[:term], limit: 5 }
    # yelp_search = Yelp.client.search(location, parameters)
    # @results = yelp_search.businesses

    if @item.save
      redirect_to controller: "playlists", action: "show", id: @playlist.id
    else
      render :new
    end

  end

  def show
  end

  def edit
  end

  def update
  end

  def destroy
  end

  protected

  def item_params
    params.require(:item).permit(:name)
  end

end

foodify/app/controllers/playlist_controller.rb
class PlaylistController < ApplicationController

  def new
    if current_user
      @playlist = Playlist.new
    else
      redirect_to new_user_session_path
    end
  end

  def create
    @playlist = Playlist.new(playlist_params)
    @playlist.user = current_user
    if @playlist.save
      redirect_to user_playlist_path(@playlist.id)
    else
      render :new
    end
  end

  def show
    @playlist = Playlist.find(params[:id])
    @items = @playlist.items
  end

  def edit
  end

  def update
  end

  def destroy
  end

  def playlist_params
    params.require(:playlist).permit(:name)
  end

end

foodify/app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController

  def index
    @user = User.find(params[:user_id])
    @playlists = @user.playlists
  end

  def new
    user = User.find(params[:user_id])
    if current_user == user
      @playlist = Playlist.new
    else
      redirect_to new_user_session_path
    end
  end

  def create
    @playlist = Playlist.new(playlist_params)
    @playlist.user = current_user
    if @playlist.save
      render :show
    else
      render :new
    end
  end

  def show
    @playlist = Playlist.find(params[:id])
    @items = @playlist.items
  end

  def edit
    user = User.find(params[:user_id])
    if current_user == user
      @playlist = Playlist.find(params[:id])
    else
      redirect_to new_user_session_path
    end
  end

  def update
    @playlist = Playlist.find(params[:id])
    if @playlist.update(playlist_params)
      render :show
    else
      render :edit
    end
  end

  def destroy
    @playlist = Playlist.find(params[:id])
    @playlist.destroy

    redirect_to root_path
  end

  protected

  def playlist_params
    params.require(:playlist).permit(:name)
  end

end

foodify/app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :current_password)
  end

end

foodify/app/controllers/user_controller.rb
class UserController < ApplicationController

  def show

  end


  def destroy

  end

end

foodify/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show

  end


  def destroy

  end

end

foodify/app/helpers/application_helper.rb
module ApplicationHelper
end

foodify/app/views/homes/index.html.erb
<%= form_tag search_path, method: "get", :class => "form-inline" do %>
  <%= label_tag(:term, "Search for:") %>
  <%= text_field_tag(:term) %>
  <%= label_tag(:location, "Near:") %>
  <%= text_field_tag(:location) %>
  <%= submit_tag "Search", class: "btn btn-primary" %>
<% end %>

foodify/app/views/homes/search.html.erb
<% if @results %>
  <% @results.each do |result| %>
    <li><%= result.name %> <%= result.location.display_address %></li>
  <% end %>
<% end %>

foodify/app/views/items/new.html.erb
<%= form_for @item, url: user_playlist_items_path do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, placeholder: "What is the food's name?" %>

  <!-- Search for restaurant and location using Yelp SEARCH API. This will return 5 results.
  Allow user to select the correct one out of the results that Yelp returns.
  Get the restaurant they chose, look in Restaurants table to see if it exists, if not create it.
  Add that restaurant's ID to this item.
  <%= f.label :term, "Restaurant's name?" %>
  <%= f.text_field :term %>
  <%= f.label :location, "Where is it?" %>
  <%= f.text_field :location %> -->

  <%= f.submit "Create", class: "btn btn-primary" %>
<% end %>

foodify/app/views/layouts/_navbar.html.erb
<% if current_user %>
  <li><%= link_to 'View my playlists', user_playlists_path(current_user) %></li>
  <li><%= link_to 'Add playlist', new_user_playlist_path(current_user) %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>

foodify/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Foodify</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'layouts/navbar' %>
  <%= yield %>

</body>
</html>

foodify/app/views/playlists/edit.html.erb
<%= form_for @playlist, url: user_playlist_path, :html => { :multipart => true } do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, placeholder: @playlist.name %>
  <%= f.submit "Update", class: "btn btn-success" %>
<% end %>

foodify/app/views/playlists/index.html.erb
<% if @playlists %>
  <% @playlists.each do |playlist| %>
    <li><%= link_to playlist.name, "/users/#{playlist.user.id}/playlists/#{playlist.id}" %></li>
  <% end %>
<% else %>
  <h1>You don't have any playlists yet.</h1>
<% end %>

foodify/app/views/playlists/new.html.erb
<%= form_for @playlist, url: user_playlists_path do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, placeholder: "Enter your playlist name here" %>
  <%= f.submit "Create", class: "btn btn-success" %>
<% end %>

foodify/app/views/playlists/show.html.erb
<h2><%= @playlist.name %></h2>

<% if @items %>
  <% @items.each do |item| %>
    <li><%= item.name %></li>
  <% end %>
<% end %>

<%= link_to "New item", "/users/#{@playlist.user.id}/playlists/#{@playlist.id}/items/new" %>